<a href="https://colab.research.google.com/github/thellamsneha13/sneha-thellam-repository/blob/main/DataPreprocessing_Assignment11__task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [2]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Step 2: Importing dataset**

In [4]:
df=pd.read_csv('Data.csv')
df.head(3)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [5]:
df.shape

(10, 4)

**Step 3: Handling the missing data**

In [14]:
X = df.iloc[:,:-1].values
Y = df.iloc[:,3].values


print ('X: %s'%(str(X)))
print ('-----------------------------------')
print ('Y: %s'%(str(Y)))

X: [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
-----------------------------------
Y: ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# Fit imputer for columns 1 and 2 of X matrix.
imputer = imputer.fit(X[:,1:3])

#Replace missing data with mean of column
X[:,1:3] = imputer.transform(X[:,1:3])

In [16]:
print ('X: %s'%(str(X)))
print ('-----------------------------------')
print ('Y: %s'%(str(Y)))

X: [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
-----------------------------------
Y: ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


**Step 4: Encoding categorical data**

In [17]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
X[:,0]

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

**Step 5: Creating a dummy variable**

In [18]:
labelencoder_Y = LabelEncoder()
Y = labelencoder_X.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

**Step 6: Splitting the datasets into training sets and Test sets**

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [25]:
# Print the shape of the dataset
print ('X_train: %s'%(str(X_train.shape)))
print ('----------------')
print ('X_test: %s'%(str(X_test.shape)))
print ('----------------')
print ('Y_train: %s'%(str(y_train.shape)))
print ('----------------')
print ('Y_test: %s'%(str(y_test.shape)))

X_train: (7, 3)
----------------
X_test: (3, 3)
----------------
Y_train: (7,)
----------------
Y_test: (3,)


**Step 7: Feature Scaling**

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [26]:
X_train

array([[-0.8660254 , -0.2029809 ,  0.44897083],
       [ 1.15470054, -1.82168936, -1.41706417],
       [ 1.15470054,  0.08478949, -1.0242147 ],
       [-0.8660254 ,  1.5775984 ,  1.62751925],
       [ 1.15470054, -0.04111006, -0.14030338],
       [-0.8660254 ,  0.93011502,  0.94003267],
       [-0.8660254 , -0.52672259, -0.43494049]])

In [27]:
X_test

array([[ 0.14433757, -1.33607682, -0.82778996],
       [ 0.14433757,  1.90134009,  2.02036872],
       [ 0.14433757,  0.28263164,  0.13250875]])