<a href="https://colab.research.google.com/github/thellamsneha13/sneha-thellam-repository/blob/main/Numpy_tasks_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
a = np.ones((5,12))

print("%d bytes " % (a.size * a.itemsize))

480 bytes 


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [6]:
 import numpy; 
 http://numpy.info(numpy.add)

SyntaxError: ignored

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [7]:
b=np.zeros(10)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [8]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [10]:
a8=np.arange(30)
print(a8[::-1])

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [12]:
a9=np.arange(9).reshape(3,3)
a9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [13]:
a10=[1,2,0,0,4,0]
print(np.nonzero((a10)))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [14]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [17]:
a12=np.random.random((3,3,3))
a12

array([[[0.76769129, 0.62582474, 0.20807344],
        [0.49432549, 0.6368233 , 0.85033933],
        [0.39701907, 0.23526143, 0.24461838]],

       [[0.18543072, 0.70266401, 0.54556739],
        [0.40068667, 0.95973602, 0.43761613],
        [0.6259923 , 0.47220117, 0.66614296]],

       [[0.63509677, 0.48029714, 0.6365307 ],
        [0.40308346, 0.34535491, 0.49888313],
        [0.18351811, 0.93365371, 0.80724899]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [18]:
a13=np.random.random((10,10))
print("the minimum value : : ",a13.min())
print("the maximum value : : ",a13.max())

the minimum value : :  0.013535850319055132
the maximum value : :  0.9923548221694493


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [19]:
a14=np.random.randint(30)
print(np.mean(a14))

29.0


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [23]:
a15= np.ones((10,10))
a15[1:-1,1:-1] = 0
print(a15)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [30]:
a16 = np.arange(1,10).reshape(3,3)
a16 = np.pad(a16, pad_width=1, mode='constant', constant_values=0)
print(a16)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [31]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [32]:
a18= np.diag(1+np.arange(4),k=-1)
print(a18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [33]:
a19= np.zeros((8,8),dtype=int)
a19[1::2,::2] = 1
a19[::2,1::2] = 1
print(a19)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [34]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [35]:
a21= np.tile( np.array([[0,1],[1,0]]), (4,4))

print(a21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [36]:
a22 = np.random.random((5,5))
a22max, a22min = a22.max(), a22.min()
a22 = (a22- a22min)/(a22max - a22min)
print(a22)

[[0.64201949 0.23223719 0.5520011  0.33700552 0.62194053]
 [0.18217683 0.9908737  0.3325883  0.71893729 0.14284471]
 [0.97563534 0.31637172 0.25777277 0.11236905 0.02665105]
 [0.986946   0.05867768 0.91237224 0.77088133 0.15948687]
 [0.         1.         0.07939655 0.04828956 0.09938242]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [145]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [40]:
a24= np.dot(np.ones((5,3)), np.ones((3,2)))
print(a24)

a24_1 = np.ones((5,3)) @ np.ones((3,2))  # Alternative solution, in Python 3.5 and above
print(a24_1)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [41]:
a25= np.arange(11)
a25[(3 < a25) & (a25<= 8)] *= -1
print(a25)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [43]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [197]:
z=np.arange(10)
print("\nz**z : :\n",z**z)
print("\n2 << z >> 2 : :\n",2 << z >> 2)
print("\nz <- z : :",z <- z)
print("\n1j*z : :\n",1j*z)
print("\nz/1/1 : :\n",z/1/1)
print("\nz<z<z : :\n",z<z<z)


z**z : :
 [        1         1         4        27       256      3125     46656
    823543  16777216 387420489]

2 << z >> 2 : :
 [  0   1   2   4   8  16  32  64 128 256]

z <- z : : [False False False False False False False False False False]

1j*z : :
 [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]

z/1/1 : :
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [46]:
print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [47]:
a29 = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(a29)), a29))

[-10.   6.   7.  -7.  -8.   6.  -9.  -9.   3.   8.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [49]:
ar1= np.random.randint(0,10,10)
ar2= np.random.randint(0,10,10)
print(np.intersect1d(ar1,ar2))

[0 3 5 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [147]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

In [149]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0
    print(Z)

[inf]


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [56]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [58]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("yesterday : : ",yesterday)
today = np.datetime64('today', 'D')
print("today : : ",today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("tomorrow : : ",tomorrow)

yesterday : :  2022-03-22
today : :  2022-03-23
tomorrow : :  2022-03-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [59]:
a34= np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a34)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [62]:
A = np.ones(3)*1
print(A)
B = np.ones(3)*2
print(B)
C = np.ones(3)*3
print(C)
print("add : :",np.add(A,B,out=B))
print("division : : ",np.divide(A,2,out=A))
print("negative : :",np.negative(A,out=A))
print("multiplication : : ",np.multiply(A,B,out=A))

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]
add : : [3. 3. 3.]
division : :  [0.5 0.5 0.5]
negative : : [-0.5 -0.5 -0.5]
multiplication : :  [-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [69]:
a36 = np.random.uniform(0,10,10)

print ("percenatge : : ",a36- a36%1)
print ("floor : : ",np.floor(a36))
print ("ceil : : ",np.ceil(a36)-1)
print ("astype : : ",a36.astype(int))
print ("trunc : : ",np.trunc(a36))

percenatge : :  [4. 6. 7. 3. 9. 8. 7. 7. 9. 8.]
floor : :  [4. 6. 7. 3. 9. 8. 7. 7. 9. 8.]
ceil : :  [4. 6. 7. 3. 9. 8. 7. 7. 9. 8.]
astype : :  [4 6 7 3 9 8 7 7 9 8]
trunc : :  [4. 6. 7. 3. 9. 8. 7. 7. 9. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [70]:
a37 = np.zeros((5,5))
a37+= np.arange(5)
print(a37)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [72]:
def generate():
  for x in range(10):
    yield x

a38 = np.fromiter(generate(),dtype=float,count=-1)
print(a38)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [73]:
a39 = np.linspace(0,1,12,endpoint=True)[1:-1]

print(a39)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [74]:
a40 = np.random.random(10)
a40.sort()

print(a40)

[0.01255627 0.16848631 0.40261302 0.67145283 0.73182373 0.75866022
 0.79318    0.82003314 0.94011008 0.99872484]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [75]:
a41 = np.arange(10)

np.add.reduce(a41)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [78]:
A = np.random.randint(0,2,5)

B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values

cl_equal = np.allclose(A,B)

print("Allclose : : ",cl_equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)

arr_equal = np.array_equal(A,B)

print("array_equal : : ",arr_equal)

Allclose : :  False
array_equal : :  False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [191]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [84]:
Z = np.random.random((10,2))

X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2+Y**2)

T = np.arctan2(Y,X)

print(R)

print(T)

[0.4102084  1.11625216 0.40233764 0.92349742 0.57623066 0.48213246
 0.92447682 0.69558779 0.69838898 0.52051901]
[0.70205662 0.60026241 0.74911442 1.54726633 0.61083534 0.05188064
 1.45848091 0.03723617 1.10918885 1.2588627 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [85]:
a45= np.random.random(10)

a45[a45.argmax()] = 0

print(a45)

[0.9051605  0.         0.72012549 0.66214238 0.33556639 0.85047526
 0.54964106 0.32506039 0.11919367 0.1946758 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [86]:
a46= np.zeros((5,5), [('x',float),('y',float)])

a46['x'], a46['y'] = np.meshgrid(np.linspace(0,1,5),

np.linspace(0,1,5))

print(a46)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [87]:
X = np.arange(8)

Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)

print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [88]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [190]:
np.set_printoptions(threshold=float("inf"))
a49 = np.zeros((20,20))
print(a49)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [94]:
a50= np.arange(100)

v = np.random.uniform(0,100)

index = (np.abs(a50-v)).argmin()

print(a50[index])

2


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [95]:
a51= np.zeros(10, [ ('position', [ ('x', float, 1),

('y', float, 1)]),

('color', [ ('r', float, 1),

('g', float, 1),

('b', float, 1)])])

print(a51)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  if __name__ == '__main__':


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [96]:
Z = np.random.random((10,2))

X,Y = np.atleast_2d(Z[:,0], Z[:,1])

D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

print(D)

# Much faster with scipy

import scipy

# Thanks Gavin Heverly-Coulson (#issue 1)

import scipy.spatial

Z = np.random.random((10,2))

D = scipy.spatial.distance.cdist(Z,Z)

print(D)

[[0.         0.65181603 0.13401056 0.21768803 0.268124   0.76504166
  0.76115932 0.33985264 0.19443928 0.395412  ]
 [0.65181603 0.         0.61145407 0.85711244 0.41081775 0.26469801
  0.44011272 0.95980929 0.48927243 0.91877974]
 [0.13401056 0.61145407 0.         0.32719737 0.2933663  0.76803664
  0.79980459 0.4551018  0.24558796 0.52858247]
 [0.21768803 0.85711244 0.32719737 0.         0.45297313 0.93840378
  0.89678122 0.12839428 0.37266502 0.25717799]
 [0.268124   0.41081775 0.2933663  0.45297313 0.         0.4969501
  0.50695298 0.54974105 0.08031686 0.51641383]
 [0.76504166 0.26469801 0.76803664 0.93840378 0.4969501  0.
  0.20879259 1.01659052 0.57362463 0.92670209]
 [0.76115932 0.44011272 0.79980459 0.89678122 0.50695298 0.20879259
  0.         0.95168276 0.56865166 0.8293734 ]
 [0.33985264 0.95980929 0.4551018  0.12839428 0.54974105 1.01659052
  0.95168276 0.         0.47056381 0.18947494]
 [0.19443928 0.48927243 0.24558796 0.37266502 0.08031686 0.57362463
  0.56865166 0.470563

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [97]:
a53 = np.arange(10, dtype=np.int32)

a53 = a53.astype(np.float32, copy=False)

print(a53)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [188]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [104]:
Z = np.arange(9).reshape(3,3)
print("ndenumerate : : ")
for index, value in np.ndenumerate(Z):
  print(index, value)
print("ndindex : : ")
for index in np.ndindex(Z.shape):
  print(index, Z[index])

ndenumerate : : 
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
ndindex : : 
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [105]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

D = np.sqrt(X*X+Y*Y)

sigma, mu = 1.0, 0.0

G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [106]:
n = 10

p = 3

a57 = np.zeros((n,n))

np.put(a57, np.random.choice(range(n*n), p, replace=False),1)

print(a57)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [109]:
X = np.random.rand(5, 10)

print("Recent versions of numpy\n")

Y = X - X.mean(axis=1, keepdims=True)
print(Y)

print("\nOlder versions of numpy\n")

Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

Recent versions of numpy

[[-0.33762569 -0.18955361 -0.35956872 -0.32155546  0.09957598  0.09825463
   0.26377691  0.43928606 -0.03270188  0.34011179]
 [ 0.21372627  0.15585629  0.17395134 -0.4122554  -0.22973897 -0.32068921
  -0.17787989  0.44174657 -0.06259883  0.21788184]
 [-0.34723095  0.47747429  0.26893128 -0.38863652 -0.31555524  0.33260037
   0.25871127 -0.19425538 -0.37258824  0.28054912]
 [-0.25689418  0.27835847 -0.02462722 -0.31450965 -0.15633685 -0.33748671
   0.63193271 -0.34871354 -0.10044313  0.62872008]
 [-0.28712741  0.34141345  0.46276563 -0.41865482  0.08044053 -0.40580864
  -0.48951401  0.40877263  0.37192117 -0.06420853]]

Older versions of numpy

[[-0.33762569 -0.18955361 -0.35956872 -0.32155546  0.09957598  0.09825463
   0.26377691  0.43928606 -0.03270188  0.34011179]
 [ 0.21372627  0.15585629  0.17395134 -0.4122554  -0.22973897 -0.32068921
  -0.17787989  0.44174657 -0.06259883  0.21788184]
 [-0.34723095  0.47747429  0.26893128 -0.38863652 -0.31555524  0.3326003

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [112]:
a59= np.random.randint(0,10,(3,3))

print(a59)
print("\nargsort : :\n")
print(a59[a59[:,1].argsort()])


[[7 6 2]
 [0 0 5]
 [1 3 0]]

argsort : :

[[0 0 5]
 [1 3 0]
 [7 6 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [125]:
a60= np.random.randint(0,3,(3,10))

print((~a60.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [127]:
Z = np.random.uniform(0,1,10)

z = 0.5

m = Z.flat[np.abs(Z - z).argmin()]

print(m)

0.6047203816080619


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [124]:
A = np.arange(3).reshape(3,1)

B = np.arange(3).reshape(1,3)

it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y

print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [187]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [128]:
print("\n np.bincount \n")
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))

print(Z)

print("\n np.add \n")
np.add.at(Z, I, 1)

print(Z)


 np.bincount 

[2. 1. 2. 5. 2. 3. 5. 1. 4. 5.]

 np.add 

[3. 1. 3. 9. 3. 5. 9. 1. 7. 9.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [129]:
X = [1,2,3,4,5,6]

I = [1,3,9,3,4,1]

F = np.bincount(I,X)

print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [130]:
w,h = 16,16

I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]

n = len(np.unique(F))

print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [133]:
A = np.random.randint(0,10,(3,4,3,4))

print("solution by passing a tuple of axes (introduced in numpy 1.7.0)\n")

sum = A.sum(axis=(-2,-1))

print(sum)

print("\nsolution by flattening the last two dimensions into one\n")

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)

print(sum)

solution by passing a tuple of axes (introduced in numpy 1.7.0)

[[59 57 63 52]
 [48 53 45 42]
 [44 63 46 37]]

solution by flattening the last two dimensions into one

[[59 57 63 52]
 [48 53 45 42]
 [44 63 46 37]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [134]:
D = np.random.uniform(0,1,100)

S = np.random.randint(0,10,100)

D_sums = np.bincount(S, weights=D)

D_counts = np.bincount(S)

D_means = D_sums / D_counts

print("bincount method\n")
print(D_means)

print("\nPandas solution as a reference due to more intuitive code\n")

import pandas as pd

print(pd.Series(D).groupby(S).mean())

bincount method

[0.53432951 0.56010439 0.57838644 0.51232603 0.60309785 0.54457765
 0.48978801 0.48486622 0.43959992 0.34350652]

Pandas solution as a reference due to more intuitive code

0    0.534330
1    0.560104
2    0.578386
3    0.512326
4    0.603098
5    0.544578
6    0.489788
7    0.484866
8    0.439600
9    0.343507
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [137]:
A = np.random.uniform(0,1,(5,5))

B = np.random.uniform(0,1,(5,5))

print("Slow version - np.diag\n")

print(np.diag(np.dot(A, B)))

print("\nFast version- np.sum\n")

print(np.sum(A * B.T, axis=1))

print("\nFaster version - eisum\n")

print(np.einsum("ij,ji->i", A, B))

Slow version - np.diag

[0.62818535 0.56865267 1.88672211 1.09240381 0.5545414 ]

Fast version- np.sum

[0.62818535 0.56865267 1.88672211 1.09240381 0.5545414 ]

Faster version - eisum

[0.62818535 0.56865267 1.88672211 1.09240381 0.5545414 ]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [138]:
a70= np.array([1,2,3,4,5])

nz = 3

Z0 = np.zeros(len(a70) + (len(a70)-1)*(nz))

Z0[::nz+1] = a70

print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [139]:
A = np.ones((5,5,3))

B = 2*np.ones((5,5))

print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [140]:
A = np.arange(25).reshape(5,5)

A[[0,1]] = A[[1,0]]

print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [141]:
faces = np.random.randint(0,100,(10,3))

F = np.roll(faces.repeat(2,axis=1),-1,axis=1)

F = F.reshape(len(F)*3,2)

F = np.sort(F,axis=1)

G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )

G = np.unique(G)

print(G)

[( 3, 65) ( 3, 97) ( 9, 10) ( 9, 58) (10, 58) (15, 18) (15, 56) (15, 63)
 (15, 74) (18, 74) (21, 33) (21, 92) (23, 47) (23, 84) (25, 30) (25, 45)
 (30, 45) (33, 92) (35, 42) (35, 83) (39, 49) (39, 91) (42, 83) (47, 84)
 (49, 91) (56, 63) (63, 67) (63, 86) (65, 97) (67, 86)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [142]:
C = np.bincount([1,1,2,3,4,4,6])

A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [143]:
def moving_average(a, n=3) :
  ret = np.cumsum(a, dtype=float)
  ret[n:] = ret[n:] - ret[:-n]
  return ret[n - 1:] / n

Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [144]:
from numpy.lib import stride_tricks

def rolling(a, window):
  shape = (a.size - window + 1, window)
  strides = (a.itemsize, a.itemsize)
  return stride_tricks.as_strided(a, shape=shape, strides=strides)

a76 = rolling(np.arange(10), 3)

print(a76)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [152]:
Z = np.random.randint(0,2,100)

np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)

np.negative(Z, out=Z)

array([ 0.09390832, -0.92091171, -0.01642569,  0.05435517,  0.74692898,
       -0.77122829,  0.32165627,  0.24290407, -0.99687336, -0.08321621,
        0.79153279,  0.66139255,  0.17424041, -0.62916284, -0.16056089,
       -0.17682498, -0.78435412, -0.14222644, -0.37211387, -0.70070509,
       -0.47941547,  0.86974674, -0.23952514,  0.39205063, -0.67852801,
        0.62472759,  0.9572648 , -0.31259367, -0.10399255, -0.36668908,
       -0.94678258,  0.13082419, -0.58496161,  0.99513507,  0.31076565,
        0.29264024,  0.05760435, -0.43685154, -0.50717737,  0.42647713,
        0.8893804 ,  0.6338121 , -0.51599236, -0.68289756, -0.00712691,
       -0.12635751, -0.89968427,  0.45520118, -0.91714058,  0.86406373,
       -0.9763501 ,  0.48101926, -0.94994709,  0.76752704,  0.55028755,
        0.38439019, -0.8277285 , -0.38187824,  0.96574724,  0.60509139,
       -0.81547987,  0.90462168, -0.5363627 ,  0.87674452,  0.15970864,
        0.48481339,  0.80383599, -0.01975799, -0.40592276, -0.97

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [153]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[12.66497817  3.91659052  4.22776016  4.54761092 12.85209062  0.09431241
  8.79621664  6.24603028  4.84163629  2.03652303]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [154]:

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[1.43511522e+01 1.20130624e+00 3.65785307e+00 1.62594166e+01
  1.10971061e+01 2.04917106e-01 2.41034972e-01 8.48750313e+00
  2.44535456e+00 6.89275958e+00]
 [1.30651718e+01 3.06018540e+00 9.37256417e-01 1.16156205e+01
  9.24306655e+00 5.32868742e+00 4.68793704e-02 4.48865768e+00
  2.14429777e+00 1.53322418e+00]
 [1.27883428e+01 3.36496904e+00 1.28604126e+00 1.10826013e+01
  8.91656153e+00 5.88468711e+00 2.32227363e-01 3.99522244e+00
  1.95771201e+00 1.06757457e+00]
 [1.60935615e+01 8.56938895e+00 6.36666549e+00 1.07100445e+01
  1.17666843e+01 8.41635978e+00 3.76176767e+00 4.58290588e+00
  5.94351179e+00 3.30622124e+00]
 [9.69484044e+00 1.21783226e+00 3.16780536e+00 1.12117167e+01
  6.21483777e+00 3.81407736e+00 3.91233451e+00 3.27230964e+00
  1.71547366e+00 4.83742773e+00]
 [9.96486742e+00 2.77735782e+00 4.82756611e+00 1.26931594e+01
  6.68293206e+00 1.96288323e+00 3.98574804e+00 4.51062758e+00
  1.78440077e+00 6.70945032e+00]
 [6.47048479e+00 6.41758778e+00 5.16562912e+00 1.89124112e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [155]:

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 0 9 5 7 8 8 5 8 8]
 [8 3 5 2 9 4 6 0 1 4]
 [0 1 5 7 1 2 8 6 7 4]
 [1 0 3 5 5 4 2 5 4 9]
 [3 4 4 8 9 8 8 4 2 9]
 [7 6 5 4 0 9 3 5 4 8]
 [4 3 1 0 8 3 3 2 5 1]
 [6 1 7 5 9 4 6 7 0 9]
 [2 5 5 7 8 1 4 5 3 7]
 [4 9 9 6 3 6 2 6 4 6]]
[[0 0 0 0 0]
 [0 0 0 9 5]
 [0 8 3 5 2]
 [0 0 1 5 7]
 [0 1 0 3 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [156]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [157]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [159]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [160]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  6 10  1 14]
 [ 6  1  9  5  3]
 [10  9  5 42 17]
 [ 1  5 42  2 15]
 [14  3 17 15  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [161]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [162]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [163]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [164]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [165]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [166]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [186]:
x = np.random.rand(int(5e7))

print("np.power : : \n",np.power(x,3))
%timeit np.power(x,3)
print("np.* : : \n",x*x*x)
%timeit x*x*x
print("np.eisum : : \n",np.einsum('i,i,i->i',x,x,x))
%timeit np.einsum('i,i,i->i',x,x,x)

np.power : : 
 [0.3016295  0.05935103 0.00118818 ... 0.44721744 0.66652081 0.3506451 ]
1 loop, best of 5: 3.74 s per loop
np.* : : 
 [0.3016295  0.05935103 0.00118818 ... 0.44721744 0.66652081 0.3506451 ]
10 loops, best of 5: 141 ms per loop
np.eisum : : 
 [0.3016295  0.05935103 0.00118818 ... 0.44721744 0.66652081 0.3506451 ]
10 loops, best of 5: 124 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [168]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [169]:
Z = np.random.randint(0,5,(10,3))
print(Z)
print("solution for arrays of all dtypes (including string arrays and record arrays)")
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
print("soluiton for numerical arrays only, will work for any number of columns in Z")
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 0 4]
 [0 0 1]
 [4 4 0]
 [2 0 1]
 [4 2 1]
 [3 4 1]
 [1 0 4]
 [2 1 3]
 [1 4 1]
 [1 1 2]]
solution for arrays of all dtypes (including string arrays and record arrays)
[[2 0 4]
 [0 0 1]
 [4 4 0]
 [2 0 1]
 [4 2 1]
 [3 4 1]
 [1 0 4]
 [2 1 3]
 [1 4 1]
 [1 1 2]]
soluiton for numerical arrays only, will work for any number of columns in Z
[[2 0 4]
 [0 0 1]
 [4 4 0]
 [2 0 1]
 [4 2 1]
 [3 4 1]
 [1 0 4]
 [2 1 3]
 [1 4 1]
 [1 1 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [171]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
print("\n np.upackbits method : :\n")

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]

 np.upackbits method : :

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [172]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [174]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

print("sum : : \n",np.einsum('i->', A))       # np.sum(A)
print("multiplicati : : \n ",np.einsum('i,i->i', A, B))   # A * B
print("inner : : \n", np.einsum('i,i', A, B))    # np.inner(A, B)
print("outer : : \n",np.einsum('i,j->ij', A, B))    # np.outer(A, B)

sum : : 
 4.029953879964494
multiplicati : : 
  [0.08304074 0.5068726  0.15813906 0.46629456 0.03373726 0.19175496
 0.19663527 0.24424575 0.18297761 0.02328954]
inner : : 
 2.0869873603647684
outer : : 
 [[0.08304074 0.42984138 0.11913408 0.37014472 0.14197017 0.23698036
  0.22770405 0.19924302 0.31535125 0.30778775]
 [0.09792234 0.5068726  0.14048391 0.43647779 0.16741243 0.27944925
  0.26851055 0.23494906 0.37186486 0.36294592]
 [0.11022862 0.57057322 0.15813906 0.49133162 0.18845179 0.3145687
  0.3022553  0.26447601 0.41859854 0.40855872]
 [0.10461164 0.5414982  0.15008068 0.46629456 0.17884874 0.29853905
  0.28685311 0.25099896 0.39726778 0.38773957]
 [0.01973349 0.1021459  0.02831058 0.08795981 0.03373726 0.05631513
  0.05411074 0.04734737 0.07493889 0.07314153]
 [0.06719322 0.34781034 0.0963985  0.2995062  0.11487654 0.19175496
  0.18424895 0.16121943 0.25516953 0.24904945]
 [0.07171035 0.37119223 0.10287898 0.3196408  0.12259923 0.20464588
  0.19663527 0.17205757 0.27232355 0.26

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [182]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
print("\nr_int::\n",r_int)
print("\nx_int::\n",x_int)
print("\ny_int::\n",y_int)


r_int::
 [  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 18

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [177]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [180]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print("percentile ::\n",confint)

percentile ::
 [0.00869433 0.34365277]
